### ISSUE TITLE
Todo for new release

### ISSUE THREAD

**Issue by jonathan-s** [jazzband/django-dbbackup#350]
- [ ] Write a changelog for all the changes since 3.2.0 related to #242 
- [x] Close this issue when released https://github.com/django-dbbackup/django-dbbackup/issues/325
- [x] There's already a 3.3.0 release. So need to make a correct tag for that. 
- [ ] Close #213 when released as that issue should be solved with that. 
- [ ] Go through the doc tags and write documentation for those. 
- [ ] Linting should happen after unittests. 
- [ ] Upload automatically with tags as described in a prior PR
- [ ] Automatic writing of changelog automation.

**Comment by johnthagen** [comment]
@jonathan-s To help with maintenance, you could consider applying to join [JazzBand](https://jazzband.co/).
